name: eSamudaay
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.29+108

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.6+2
  #flutter_redux_dev_tools: ^0.4.0
  flutter_offline: ^0.3.0
  path_provider: any
  http: ^0.12.0+4
  dio: ^3.0.8
  connectivity: ^0.4.8+1
  intl: ^0.16.0
  easy_alert: ^0.0.8
  carousel_slider: ^1.4.1
  redux_persist_flutter: ^0.8.2
  cached_network_image: ^2.0.0
  equatable: ^1.1.0
  async_redux: ^2.5.4
  flutter_slidable: ^0.5.4
  easy_localization: ^2.1.0+2
  regexed_validator: ^1.0.2
  fluttertoast: ^4.0.1
  expandable: ^4.1.3
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  flutter_rating_bar: ^3.0.1+1
  firebase_messaging: ^6.0.16
  url_launcher: ^5.4.11
  image_picker: ^0.6.7+2
  pull_to_refresh: 1.6.0
  firebase_crashlytics: ^0.4.0+1
  firebase_core: ^0.7.0
  flutter_staggered_animations: ^0.1.2
  status_alert: ^0.1.2
  dropdown_formfield: ^0.1.2
  smooth_page_indicator: ^0.2.0
  package_info: ^0.4.0+16
  location: ^3.0.2
  fm_fit: ^0.0.3
  video_player: ^0.10.12+3
  chewie: ^0.9.10
  firebase_dynamic_links: ^0.7.0+1
  share: ^0.6.5+4
  visibility_detector: ^0.1.5
  flutter_shimmer: ^1.3.0
  google_maps_flutter: ^1.0.6
  geocoder: ^0.2.1
  uuid: ^2.2.2
  google_maps_webservice: ^0.0.18
  app_settings: ^4.0.4
  razorpay_flutter: ^1.2.2
  lottie: ^0.7.0+1
  rounded_loading_button: ^1.0.18
  firebase_analytics: ^7.0.1
  device_info: ^1.0.0
  flutter_typeahead: ^2.0.0
  pin_code_fields: ^6.1.0
  intl_phone_number_input: ^0.6.0

  esamudaay_app_update:
    git:
      url: https://anushka_agrawal@bitbucket.org/ese1/esm_comp_appupdate.git
      ref: v0.0.1

  esamudaay_themes:
    git:
      url: https://anushka_agrawal@bitbucket.org/ese1/esm_comp_themes.git
      ref: v0.0.1

  esamudaay_image_services:
    git:
      url: "https://anushka_agrawal@bitbucket.org/ese1/esm_comp_imageservices.git"
      ref: v0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/Avenir-Book.ttf
        - asset: assets/font/Avenir-Medium.ttf
        - asset: assets/font/Archivo-Medium.ttf
        - asset: assets/font/Lato-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/languages/en-US.json
    - assets/languages/ka-IN.json
    - assets/languages/ml-IN.json
    - assets/languages/ta-IN.json
    - assets/languages/te-IN.json
    - assets/languages/hi-Deva-IN.json
    - assets/images/Component 6 – 1.png
    - assets/images/app_main_icon.png
    - assets/images/location_1_add.png
    - assets/images/bag2.png
    - assets/images/location2.png
    - assets/images/notification.png
    - assets/images/path5.png
    - assets/images/path330.png
    - assets/images/path338.png
    - assets/images/search_icon.png
    - assets/images/fruits.png
    - assets/images/banner.png
    - assets/images/delivery.png
    - assets/images/no_delivery.png
    - assets/images/shop1.png
    - assets/images/shop2.jpg
    - assets/images/fruits.jpg
    - assets/images/dairy-products.jpg
    - assets/images/groceries.jpg
    - assets/images/medicine.jpg
    - assets/images/soft-drink.jpg
    - assets/images/snack.jpg
    - assets/images/home41.png
    - assets/images/Group_240.png
    - assets/images/power.png
    - assets/images/clipart.png
    - assets/images/AI_user.png
    - assets/images/question_cr.png
    - assets/images/AI_chat.png
    - assets/images/user.jpg
    - assets/images/align2.png
    - assets/images/pen2.png
    - assets/images/group236.png
    - assets/images/indicator.gif
    - assets/images/splash.png
    - assets/images/upi.png
    - assets/images/phonePe.png
    - assets/images/gpay.png
    - assets/images/paytmLogo.png
    - assets/images/
    - assets/images/dialog.png
    - assets/images/first.png
    - assets/images/holdingMobile.png
    - assets/images/esamudayDelivery.png
    - assets/images/family.png
    - assets/images/allHands.png
    - assets/images/notepad.png
    - assets/images/refresh_1.png
    - assets/images/HeaderImage.png
    - assets/images/whatsapp.png
    - assets/images/category_placeholder.png
    - assets/images/top_banner_placeholder.jpg
    - assets/images/profile_placeholder.png
    - assets/images/circle_tile_placeholder.png
    - assets/images/cart_placeholder.png
    - assets/images/Icon_list_upload.png
    - assets/lottie/payment-failed.json
    - assets/lottie/payment-successful.json
    - assets/images/icon_closed.png
    - assets/images/Icon_Payment.png
    - assets/images/Icon_RetryPayment.png
    - assets/images/language_selection_backdrop.png
    - assets/images/login_signup_backdrop.png
    - assets/images/landing_page_banner.png
    - assets/images/pay_icon.png
    - assets/images/icon_cash.png
    - assets/images/RazorPay_logo.png
    - assets/images/cash_grey_icon.png
    - assets/images/support_icon.png
    - assets/images/call_icon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
